name: Build and Push Docker Image

on:
  push:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Extract base tag
        id: mc
        run: |
          tag=$(grep -Eo '^FROM[[:space:]]+minio/mc:[^ ]+' Dockerfile \
                | head -n1 | cut -d':' -f2)
          echo "tag=$tag" >>"$GITHUB_OUTPUT"

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5.8.0
        with:
          images: |
            name=ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=${{ steps.mc.outputs.tag }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6.18.0
        with:
          push: true
          context: .
          file: Dockerfile
          # platforms: linux/386,linux/amd64,linux/arm,linux/arm64
          pull: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
